variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Building the project..."
    - .\build-assimp.bat
    - .\ci-scripts\build_job.bat
  artifacts:
    paths:
    - build/
    expire_in: 1 day

test_job:
  stage: test
  script:
    - echo "Running tests..."
    - .\ci-scripts\test_job.bat
