variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - prepare
  - build
  - test
  - deploy

check_format:
  stage: prepare
  scripts:
    - python .\scripts\format_code.py
    - python .\scripts\get_git_changed_files.py

shader_generation:
  stage: prepare
  script:
    - python generate_shader.py

build_debug:
  stage: build
  script:
    - echo "Building project..."
    - .\scripts\ci_build_job.bat Debug
  artifacts:
    paths:
    - build/

build_release:
  stage: build
  script:
    - echo "Building the project..."
    - .\scripts\ci_build_job.bat Release
  artifacts:
    paths:
    - build/

test_job:
  stage: test
  script:
    - echo "Running tests..."
    - .\scripts\ci_test_job.bat
