#pragma once

#define MATH_ENABLE_SIMD IN_USE

#if USING(MATH_ENABLE_SIMD)
#if USING(ARCH_X64)
#define MATH_ENABLE_SIMD_SSE  IN_USE
#define MATH_ENABLE_SIMD_NEON NOT_IN_USE
#include <xmmintrin.h>
#elif USING(ARCH_ARM64)  // #if USING(ARCH_X64)
#define MATH_ENABLE_SIMD_SSE  NOT_IN_USE
#define MATH_ENABLE_SIMD_NEON IN_USE
#include <arm_neon.h>
#else  // #elif USING(ARCH_ARM64) // #if USING(ARCH_X64)
#define MATH_ENABLE_SIMD_SSE NOT_IN_USE
#define MATH_ENABLE_SIMD_AVX NOT_IN_USE
#endif  // #else // #elif USING(ARCH_ARM64) // #if USING(ARCH_X64)
#else   // #if USING(MATH_ENABLE_SIMD)
#define MATH_ENABLE_SIMD_SSE NOT_IN_USE
#define MATH_ENABLE_SIMD_AVX NOT_IN_USE
#endif  // #else // #if USING(MATH_ENABLE_SIMD)
