option(BUILD_GLFW "Enable GLFW" ON)

if (EMSCRIPTEN)
    set(BUILD_GLFW OFF CACHE BOOL "" FORCE)
endif()

if (BUILD_GLFW)
    set(GLFW_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
    set(GLFW_BUILD_TESTS OFF CACHE BOOL "" FORCE)
    set(GLFW_BUILD_DOCS OFF CACHE BOOL "" FORCE)
    set(GLFW_INSTALL OFF CACHE BOOL "" FORCE)
    add_subdirectory(thirdparty/glfw)
    set_target_properties(glfw PROPERTIES FOLDER thirdparty)
    set_target_properties(update_mappings PROPERTIES FOLDER thirdparty)
endif()
